Squashed commit of the following:
commit edd8d1411c4fd424c25249a1934fdc25db7af9c4
Merge: 660ee2c 095b7e1
Author: Emil Zackrisson <51415707+EmilZackrisson@users.noreply.github.com>
Date:   Thu Dec 29 14:49:12 2022 +0100

    Merge pull request #1 from EmilZackrisson/build_fixes

    Build fixes

commit 095b7e13648b704319000764897ff36a14d01c38
Merge: 660ee2c f094372
Author: Emil Zackrisson <51415707+EmilZackrisson@users.noreply.github.com>
Date:   Thu Dec 29 14:48:22 2022 +0100

    Merge branch 'home-assistant:main' into build_fixes

commit 660ee2cb65bcc2f1281c2217f8a9d0c91e431162
Author: Emil Zackrisson <emil.zackrisson@gmail.com>
Date:   Thu Dec 29 14:41:51 2022 +0100

    fix build errors

commit 98b3df041ed1e626bb5596af3aa37b2a8969683c
Author: Emil Zackrisson <emil.zackrisson@gmail.com>
Date:   Thu Dec 29 14:32:22 2022 +0100

    remove domains from _fixture.yaml

commit f09437215890392b485f4b5717f6f73ab8035760
Author: João Gonçalves <1141380@isep.ipp.pt>
Date:   Thu Dec 29 13:31:48 2022 +0000

    New skip_word and error message "no_entity" tweak (#186)

commit 7b3f1498ab4d4a8e11bf5b18ef91c41ae535bf75
Author: Emil Zackrisson <emil.zackrisson@gmail.com>
Date:   Thu Dec 29 14:28:22 2022 +0100

    Fixes PR 145

commit 556d1c4f1f54429cde1c64fef1b4a15c9b1e8ef0
Author: TheFes <thefes+git@gmail.com>
Date:   Thu Dec 29 14:18:50 2022 +0100

    [NL] Update cover sentences (#183)

    * [NL] Upatete cover sentences

    * added tests to open cover

    * revert changes to incorrectly added file

    * add missing files :)

    * remove changes to wrong file (2nd try)

commit 78613430c7dda465d84bcdd31fdeed0aef6905e6
Author: Aalian Khan <39784853+AalianKhan@users.noreply.github.com>
Date:   Wed Dec 28 23:57:02 2022 -0500

    Add Urdu Language leader (#174)

    Co-authored-by: Paulus Schoutsen <balloob@gmail.com>

commit 9900ff13a6862ea7ce675e14e833db86c478b4b8
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Wed Dec 28 23:42:10 2022 -0500

    Typo

commit 34ed3195bda3cda83a8bc47e43bff8f1f7e94825
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Wed Dec 28 23:41:07 2022 -0500

    remove activate for ghpages

commit 2112769b1f72216a2dba43fd8017d294892f09e0
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Wed Dec 28 23:39:35 2022 -0500

    Do not create venv in gh-pages

commit be0e61c05eecc5dbb2cb7ecb606aeff33cbf1988
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Wed Dec 28 23:33:39 2022 -0500

    Add website (#181)

    * add summary command

    * Add website foundation

    * Add website deploy

    * Rename summary -> website_summary

    * Typing

commit 50e64482a730aa3c8a0f6653b61ce431f5d2e10f
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Wed Dec 28 22:35:43 2022 -0500

    Add domain to intents (#180)

    * Add domain to intents

    * reinstate change

commit d4638ca8527ab119dcacc332b29a226c64c7bc9e
Author: Michael Hansen <mike@rhasspy.org>
Date:   Wed Dec 28 19:22:19 2022 -0600

    Add apostrophe to valid sentence characters (#179)

commit 42881aac0ac898b7471eae94efd06ee1103a3576
Author: Michael Hansen <mike@rhasspy.org>
Date:   Wed Dec 28 17:20:33 2022 -0600

    Add empty Chinese (zh) templates (#178)

commit 5e7748e58a9d37ff03ce00205db7b3871b45ce02
Author: Andrei Solodovnikov <VoultBoy@yandex.ru>
Date:   Thu Dec 29 02:03:52 2022 +0300

    Add Russian language leader (#177)

    * Add Russian language leader

    * Add Russian native name to languages.yaml

commit ed95151ae8002fd4e61b772184d49ec6e561f8cc
Author: Andrei Solodovnikov <VoultBoy@yandex.ru>
Date:   Thu Dec 29 01:45:48 2022 +0300

    Add russian language support (#175)

commit c55ce3a875b54ef1c609b97cbe332d183e6b06ab
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Wed Dec 28 17:35:22 2022 -0500

    Add languages yaml (#176)

    * Add languages.yaml

    * Update add_language

    * Typing

    * Update CI

    * Update docs

commit ea42ef472b6463d7b784e866229a1afb34a49c49
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Wed Dec 28 16:37:47 2022 -0500

    Rename Danish from DK to DA (#173)

commit 55296e99481890f72898c5348f320b69333c2b85
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Wed Dec 28 21:23:28 2022 +0000

    Make sure languages are always sorted

commit a455e1e483192e49b3fe3f350ed30b11a01c1ba9
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Wed Dec 28 21:17:15 2022 +0000

    sort commands in argparser intentfest

commit 7a92a56237c99758df8cdc4eb2cb58ef92b58e3a
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Wed Dec 28 20:27:32 2022 +0000

    Validate as part of running tests

commit 5b128460d2e5cac45d3ff40b890263d2bb44bc34
Author: Rafael Piñero Jiménez <rafael.pinerojimenez@telefonica.com>
Date:   Wed Dec 28 21:14:46 2022 +0100

    [ES] More color options (#170)

commit 2af4c20de0060a83ca75b8263da389178c3f8c8e
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Wed Dec 28 15:10:46 2022 -0500

    Fix validate area IDs check

commit 9bd158f7f3875e026d802764d99f6c7088ff37af
Author: Andrei Solodovnikov <VoultBoy@yandex.ru>
Date:   Wed Dec 28 22:49:43 2022 +0300

    Fix command to add new language (#172)

    When trying to run command as in example:
    python3 -m script.intentfest add-language <lang_code> following error appeared:
    error: argument action: invalid choice: 'add-language' (choose from 'add_language', 'validate', 'parse', 'sample', 'sample_template')

commit 0194f24b6ff79bb767d07815d2f3e3d2b6349f72
Author: Alexandre Vieira <23476569+Alexivia@users.noreply.github.com>
Date:   Wed Dec 28 12:42:05 2022 +0000

    [PT] Added Portuguese sentences (#169)

    * started adding portuguese common words and some sentences

    * sentences for closing covers

    * finished the remaining sentences;
    slightly improved zone expansion rules;

    * modified responses;
    started modifying tests;

    * fixed indentation problems

    * fixed indentation problems

    * fixed slot usage;
    fixed color mapping by using in-out;

    * fixed mis-use of slots;
    added one more skipped word;

    * added more tests for temperature getting and setting

    * added tests for opening and closing covers

    * made tests for fans;
    made tests for generic on off;
    fixed fan sentences;
    added one more slot combination to allow for name+area slots;

    * added tests for setting light and corrected sentences definitions

    * added tests for lights on and off

    * added missing tests on light set;
    added female variant of supported colors;

commit f26f984319f37167a879c4ad7f5162f74d529457
Author: cvladan <cvladan@gmail.com>
Date:   Wed Dec 28 13:38:38 2022 +0100

    [SR] Light sentences (#168)

    * Errors Only

    * Lights

    * Finished light sentences and tests

commit cf792e70663ebf145d519685a47ab52780dd1754
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Tue Dec 27 22:38:19 2022 -0500

    Spelling updates

commit 28a275250a82d4172acca168ec3dd3a21e3f5e61
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Tue Dec 27 22:35:05 2022 -0500

    Validate to guard no question marks added to sentences (#166)

commit 144e7b0725a6e494a312c0ac65228015bd0765d0
Author: Oleksandr Kapshuk <alexkas2@gmail.com>
Date:   Wed Dec 28 05:13:54 2022 +0200

    [uk]Added fan intents (#158)

commit a3d667c07cfb4c7ba65a1577eca8f24c6c79cee4
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Tue Dec 27 22:05:39 2022 -0500

    Validate area ids correct (#165)

    * Validate that all area IDs used in fixtures are correct

    * Fix Polish area name

commit 808d33931e5c7380d040a4238add49ba886847cb
Author: David Girón <contacto@duhowpi.net>
Date:   Wed Dec 28 02:40:05 2022 +0100

    [CA] Initial Catalan language support (#111)

    * initial Catalan intents

    * Adding some initial sentences and tests for CA

    * Remove redundant quotes

    * Add missing sentences and tests

    * Update expansion_rules and sentences/tests

    * Fix conflict "close curtains" with "turn off"

    Light can be "closed" as in "turn off"

    * Update fan test

    * Add response for temperature

    * Fix test

    Co-authored-by: jorclaret <98229289+jorclaret@users.noreply.github.com>
    Co-authored-by: Paulus Schoutsen <balloob@gmail.com>

commit ef795a9d4b430d73755445964fc76d75e72a1f77
Author: Rafael Piñero Jiménez <rafael.pinerojimenez@telefonica.com>
Date:   Wed Dec 28 02:15:23 2022 +0100

    [ES] commons yaml fixes in spanish (#159)

    * commons in spanish and catalan

    * Revert catalan changes

    * Revert catalan changes

    * new skip_word

commit 213fcc96fa0b4660afbb279c04710f5f7a627c3d
Author: cvladan <cvladan@gmail.com>
Date:   Wed Dec 28 02:11:04 2022 +0100

    Errors Only (#156)

commit c4b64c76bf8b0ff8ec1b2fd261b3ff03618e300a
Author: hugovsky <89551642+hugovsky@users.noreply.github.com>
Date:   Tue Dec 27 23:29:53 2022 +0000

    First Portugese translations (#162)

    * First translations

    * Corrected some typos and files

    * Corrected the code

commit f789c8ced44400fe002e1b72385010d8aca3f887
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Tue Dec 27 09:32:17 2022 -0500

    Update CONTRIBUTING.md

commit ff060725198a632abb82be5f40274ad1cb662f09
Author: leranp <liran.kesar@gmail.com>
Date:   Tue Dec 27 15:03:34 2022 +0200

    [HE] Added Hebrew language (#154)

    * Adding initial Hebrew support for sentences. (#32)

    * Adding initial Hebrew support for sentences.

    * Update sentences/he/homeassistant_HassTurnOn.yaml

    Co-authored-by: Yuval Aboulafia <yuval.abou@gmail.com>

    * Translated more and set owner.

    * Deleted Toggle sentences

    * update the color with the in-out format

    Co-authored-by: Shay Levy <levyshay1@gmail.com>
    Co-authored-by: Yuval Aboulafia <yuval.abou@gmail.com>
    Co-authored-by: leranp <liran.kesar@gmail.com>

    * Create _fixtures.yaml

    * Add files via upload

    * Create HassClimateGetTemperature.yaml

    * fix sentences in hebrew

    * more fix and tests

    * Merge code owners

    * Update README.md

    * Fix Tests

    * More fixes

    Co-authored-by: haim-b <57748903+haim-b@users.noreply.github.com>
    Co-authored-by: Shay Levy <levyshay1@gmail.com>
    Co-authored-by: Yuval Aboulafia <yuval.abou@gmail.com>

commit f2b37e9b32d8f35b6b50b4efc335677dc0c87fef
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Mon Dec 26 23:50:08 2022 -0500

    Clean up contribution.md

commit a33b76c7bc5d4e9eba531ff4778517f3802551ec
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Mon Dec 26 23:36:00 2022 -0500

    Add VSCode task to test current file or language (#151)

    * Add VSCode task to test current file or language

    * Update codespaces docs

commit e1b1ce852fa241da86e2076bce936b998f6bdbf6
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Mon Dec 26 22:51:09 2022 -0500

    Make test output slightly more readable if slot missing (#152)

commit 8d859cafd8da542d64815668e854e11c7dfd3a46
Author: Joan <joan@fisbein.com>
Date:   Tue Dec 27 03:22:44 2022 +0100

    [ES] Initial spanish language support (#126)

    * Initial spanish sentences

    * initial spanish responses

    * Initial spanish tests

    * Adding missing expansions

    * Imporve sentences and fix tests

    * Update errors

    * Update sentences/es/climate_HassClimateGetTemperature.yaml

    Co-authored-by: Paulus Schoutsen <paulus@home-assistant.io>

commit ea34393bab8bae8475b8b931af5bcfd72d6153db
Author: dsimop <dsimop@users.noreply.github.com>
Date:   Tue Dec 27 04:06:50 2022 +0200

    Update HassClimateGetTemperature.yaml (#146)

commit e42e4488e3143a1786d129c75f0d1167ff225400
Author: Oleksandr Kapshuk <alexkas2@gmail.com>
Date:   Tue Dec 27 04:06:12 2022 +0200

    [UK] Added Ukrainian language (#144)

    * Added ukrainian language

    * Added fixtures

    * Added responses

    * Added more commons

    * Added light intents

commit 9c7472d15a7cd040919e7a4ffc30651fc998e430
Author: Alexandre Vieira <23476569+Alexivia@users.noreply.github.com>
Date:   Tue Dec 27 03:05:04 2022 +0100

    fix wrong language in area (#149)

    Area name was in Dutch instead of English.
    Missing double-quotes for consistency in file.

commit 31e178398ef45445b287429a6be4aa9a712277e0
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Mon Dec 26 11:26:13 2022 +0200

    Bump isort from 5.11.3 to 5.11.4 (#142)

    Bumps [isort](https://github.com/pycqa/isort) from 5.11.3 to 5.11.4.
    - [Release notes](https://github.com/pycqa/isort/releases)
    - [Changelog](https://github.com/PyCQA/isort/blob/main/CHANGELOG.md)
    - [Commits](https://github.com/pycqa/isort/compare/5.11.3...5.11.4)

    ---
    updated-dependencies:
    - dependency-name: isort
      dependency-type: direct:production
      update-type: version-update:semver-patch
    ...

    Signed-off-by: dependabot[bot] <support@github.com>

    Signed-off-by: dependabot[bot] <support@github.com>
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

commit 525086657ddcf7d05ab84e46f8d0d76108005a73
Author: Scorpoon <22363852+Scorpoon@users.noreply.github.com>
Date:   Mon Dec 26 10:05:14 2022 +0100

    Added the "--intents" option for "Test sampling sentences" (#136)

    * Added the "--intents" option for "Test sampling sentences"

    * Update README.md

    Co-authored-by: Paulus Schoutsen <paulus@home-assistant.io>

    Co-authored-by: Paulus Schoutsen <paulus@home-assistant.io>

commit f0210f604d61e818442b89866769a20b10e9d5e2
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Sun Dec 25 23:15:06 2022 -0500

    Add more types to tests (#140)

commit 038dac25f2c7078b76697ff2787db9ab8e6a24a7
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Sun Dec 25 22:58:00 2022 -0500

    Remove unused continue statement

commit af9d7d4df85c9f0fc4d18666ea5cd1a1d0e48e8a
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Sun Dec 25 22:39:58 2022 -0500

    Update test docs

commit 51496475a1ff07df0e0f404e58135c8aa7fde080
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Sun Dec 25 22:29:08 2022 -0500

    Split language intents tests by file (#131)

    * Split language intents by file

    * isort

    * cleanup

    * remove stale comment

    * Re-use parsed common intents

    * Remove validate logic that is also checked in tests

    * Document individual file testing

    * typo

    * Verify duplicate sentence being tested in tests instead of validate

    * Extract common validate logic into helper function

commit 69ecabd0df3fd6b639a147e698bf53833db08d9e
Author: Nerdix <70015952+N3rdix@users.noreply.github.com>
Date:   Sun Dec 25 17:45:17 2022 +0100

    Minor adjustments (#133)

    Versuch etwas näher an den englischen Ausdrücken zu bleiben.
    Einheiten sind im deutschen groß geschrieben

commit 8180dd8faf4c40f63960bf6e8ee1332d09d57ed1
Author: Aalian Khan <39784853+AalianKhan@users.noreply.github.com>
Date:   Sat Dec 24 23:55:20 2022 -0500

    Add Urdu language (#81)

    * Added Urdu

    I added most sentences for urdu. However, I am not sure how to test the files

    * Fixed errors and added skip words

    Some how fixed errors the errors and added skip words

    * Added some extra words

    added skip words for urdu and english,

    * Added some test sentences

    Added some test sentences and more ways of interacting with garage door

    * Fixed more errors, errors still present

    * Fixed more errors and added more sentences

    * Update climate_HassClimateGetTemperature.yaml

    * fixed more errors

    * All errors cleared,
    just cover and turn off conflict  left

    * Commented Cover files, Ready to merge

commit c31f41fae448bf410fe7eb4d077d66f5982a8060
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Sat Dec 24 21:47:48 2022 -0500

    Make validation more strict (#130)

commit c2c9580ed3042ab5d6845b4a3f921a16ceeca8f2
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Sat Dec 24 21:23:23 2022 -0500

    Refactor tests to move some from validate to tests (#128)

    * Refactor tests to move some from validate to tests

    * Create a test per YAML file

    * Kill some fixtures

commit d137a9f9e5cd9d267f21fa981a67e14abac00801
Author: H. Árkosi Róbert <robreg@zsurob.hu>
Date:   Sat Dec 24 23:42:52 2022 +0100

    Fine tuning hu (#129)

commit a65cde177abdcf9f734cce79f1b13e93ac64b193
Author: TheFes <thefes+git@gmail.com>
Date:   Sat Dec 24 21:05:42 2022 +0100

    [NL] Add sentences to turn fans on and off (#103)

    * [NL] Merge doe_enkelvoud and doe_meervoud

    * Maak <naar> optional

    * Made all <naar>'s optional

    * Add sentences to turn fan on and off

    * fix intentname test

    * remove sentences for all fans (for now)

    * Also remove turn off all fan sentences

commit 8562af6cf4ccb5d55b097787e106d585d4750964
Author: Paulus Schoutsen <balloob@gmail.com>
Date:   Sat Dec 24 14:19:30 2022 -0500

    Validate color names are outputed in English (#119)